import { tmpdir } from "node:os";
import { join, resolve, sep } from "node:path";
import { mkdtemp, rm, stat, writeFile } from "node:fs/promises";
import type { BunPlugin } from "bun";
import { escapeForScriptTag } from "./internal/html.js";

// Pre-bundled React sources embedded at binary-compile time via import attributes.
// These files are generated by scripts/build-react-bundles.ts (run via `prepare`
// on `bun install`, or explicitly by scripts/build-binaries.ts before each
// cross-compile step). Using { type: "text" } causes bun build --compile to store
// the source strings in the binary's data section, eliminating any filesystem
// lookup at runtime on the user's machine — no node_modules/ required.
import reactSrc from "./embedded/react.js" with { type: "text" };
import reactJsxRuntimeSrc from "./embedded/react-jsx-runtime.js" with { type: "text" };
import reactDomSrc from "./embedded/react-dom.js" with { type: "text" };
import reactDomClientSrc from "./embedded/react-dom-client.js" with { type: "text" };

const EMBEDDED_REACT: Readonly<Record<string, string>> = {
  react: reactSrc,
  "react/jsx-runtime": reactJsxRuntimeSrc,
  "react-dom": reactDomSrc,
  "react-dom/client": reactDomClientSrc,
};

// BunPlugin that intercepts all bare react/react-dom imports and serves them
// from the strings embedded in the binary (EMBEDDED_REACT above). This is the
// only resolution path — no createRequire fallback — so that the test suite and
// the compiled binary exercise exactly the same code path.
const reactAliasPlugin: BunPlugin = {
  name: "ui-leaf-react-embedded",
  setup(build) {
    // Matches: react, react/jsx-runtime, react/jsx-dev-runtime,
    //          react-dom, react-dom/client, react-dom/profiling, etc.
    build.onResolve({ filter: /^react($|\/|-dom($|\/))/ }, (args) => ({
      path: args.path,
      namespace: "ui-leaf-react-embedded",
    }));

    build.onLoad({ filter: /.*/, namespace: "ui-leaf-react-embedded" }, (args) => {
      const src = EMBEDDED_REACT[args.path];
      // Return a throw-expression so the type checker sees a valid contents field;
      // the error propagates as a Bun.build failure to the caller.
      const contents =
        src ??
        `throw new Error("ui-leaf: no embedded bundle for \\"${args.path}\\". Supported: react, react/jsx-runtime, react-dom, react-dom/client.");`;
      return { contents, loader: "js" as const };
    });
  },
};

export interface BuildError {
  file: string;
  line: number;
  column: number;
  message: string;
}

export interface CompileOptions {
  /** View name or path relative to viewsRoot (e.g. "dashboard" or "dashboard.tsx"). */
  entry: string;
  /** Root directory holding .tsx view files. */
  viewsRoot: string;
  /** JSON-serializable data injected as window.__UI_LEAF__.data. Ignored when dataLoader is true. */
  data?: unknown;
  /** Browser tab title. Defaults to "ui-leaf". */
  title?: string;
  /**
   * Raw CSP string to emit as a <meta http-equiv="Content-Security-Policy"> tag.
   * Undefined / absent means no CSP meta tag is emitted.
   */
  csp?: string;
  /**
   * Extra allowed hostnames (beyond loopback defaults). Accepted in the
   * option bag for API symmetry with DevServerOptions; has no compile-time
   * effect — the runtime DNS-rebinding gate lives in the server.
   */
  allowedHosts?: string[];
  /**
   * Per-launch auth token. Accepted for API symmetry with DevServerOptions;
   * the token is no longer embedded in HTML — it is delivered via the URL
   * fragment and read by the inline bootstrap script.
   * @deprecated No-op since v1.0.0 — token delivery is handled by startDevServer.
   */
  token?: string;
  /**
   * When true, generate an entry that fetches data from GET /api/data at
   * render time rather than reading it from window.__UI_LEAF__.data. The
   * compiled HTML bootstrap omits the data field (only token is included).
   * Use when data is sensitive and must not be written to the HTML file.
   */
  dataLoader?: boolean;
}

/**
 * Options for compiling an inline TSX source string.
 *
 * v1.0.0 constraint: `source` is treated as a self-contained TSX string.
 * Relative imports are not supported — the string has no filesystem context
 * to resolve them against. Bare-package imports (react, react-dom) work via
 * the react-alias plugin. This is the intended contract for IPC-driven
 * view hot-swaps (AI-generated self-contained components).
 */
export interface CompileSourceOptions {
  /** Raw TSX source string to compile. Must be a self-contained component. */
  source: string;
  /** JSON-serializable data injected as window.__UI_LEAF__.data. */
  data?: unknown;
  /** Browser tab title. Defaults to "ui-leaf". */
  title?: string;
  /** Raw CSP string. Undefined / absent means no CSP meta tag. */
  csp?: string;
  /**
   * Per-launch auth token. Accepted for API symmetry; not embedded in HTML —
   * see CompileOptions.token.
   * @deprecated No-op since v1.0.0.
   */
  token?: string;
}

export interface CompileResult {
  html: string;
  errors: BuildError[];
}

// Friendly message rendered when the page is reloaded without the token fragment.
const SESSION_ENDED_HTML =
  '<div style="font-family:sans-serif;padding:2em;color:#555"><p>Session ended — re-launch the CLI to continue.</p></div>';

// Overlay rendered when the mount terminates. v1.x extension point: replaceable
// via a consumer-supplied template slot (deferred per plan-approval decision).
const CLOSED_OVERLAY_HTML =
  '<div style="font-family:sans-serif;padding:2em;color:#555"><p>This view has closed.</p></div>';

// Shared bridge injected into every compiled entry: mutation + heartbeat.
const SHARED_BRIDGE = `
async function mutate(name: string, args?: unknown): Promise<unknown> {
  const res = await fetch("/mutate", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token ? { "X-UI-Leaf-Token": token } : {}),
    },
    body: JSON.stringify({ name, args }),
  });
  const text = await res.text().catch(() => "");
  if (!res.ok) {
    let detail = text;
    try {
      const parsed: unknown = text ? JSON.parse(text) : null;
      if (parsed !== null && typeof parsed === "object" && "error" in parsed && typeof (parsed as { error: unknown }).error === "string") {
        detail = (parsed as { error: string }).error;
      }
    } catch { /* keep raw text */ }
    throw new Error("ui-leaf: mutation '" + name + "' failed (" + res.status + "): " + detail);
  }
  return text ? JSON.parse(text) : undefined;
}

async function heartbeat(): Promise<void> {
  try {
    await fetch("/heartbeat", {
      method: "POST",
      headers: token ? { "X-UI-Leaf-Token": token } : {},
    });
  } catch { /* server may have shut down; ignore */ }
}
setInterval(heartbeat, 5000);
heartbeat();

function subscribeEvents(onEvent: (ev: { type: string; [k: string]: unknown }) => void): void {
  let delay = 250;
  const budget = 30_000;
  const started = Date.now();
  let done = false;

  async function connect(): Promise<void> {
    try {
      const res = await fetch("/events", {
        headers: token ? { "X-UI-Leaf-Token": token } : {},
      });
      if (!res.ok || !res.body) throw new Error("bad status " + res.status);
      delay = 250;
      const reader = res.body.getReader();
      const dec = new TextDecoder("utf-8");
      let buf = "";
      while (true) {
        const { done: streamDone, value } = await reader.read();
        if (streamDone) break;
        buf += dec.decode(value, { stream: true });
        let idx: number;
        while ((idx = buf.indexOf("\\n\\n")) !== -1) {
          const chunk = buf.slice(0, idx);
          buf = buf.slice(idx + 2);
          for (const line of chunk.split("\\n")) {
            if (line.startsWith("data:")) {
              try {
                const ev = JSON.parse(line.slice(5).trimStart()) as { type: string; [k: string]: unknown };
                if (ev.type === "closing") done = true;
                onEvent(ev);
              } catch { /* skip malformed event */ }
            }
          }
        }
        if (done) return;
      }
    } catch {
      if (done) return;
    }
    if (done) return;
    if (Date.now() - started > budget) {
      onEvent({ type: "closing", reason: "error" });
      return;
    }
    await new Promise<void>((r) => setTimeout(r, delay));
    delay = Math.min(delay * 2, 5_000);
    void connect();
  }

  void connect();
}`;

/** Run Bun.build on `entryPath` and return the raw JS output or errors. */
async function runBunBuild(entryPath: string): Promise<{ js: string } | { errors: BuildError[] }> {
  let buildOutput: Awaited<ReturnType<typeof Bun.build>>;
  try {
    buildOutput = await Bun.build({
      entrypoints: [entryPath],
      target: "browser",
      format: "esm",
      minify: false,
      sourcemap: "none",
      // Production define ensures JSX uses react/jsx-runtime (not jsx-dev-runtime),
      // which matches the set of embedded bundles.
      define: { "process.env.NODE_ENV": '"production"' },
      plugins: [reactAliasPlugin],
    });
  } catch (err) {
    if (err instanceof AggregateError) {
      type BunBuildMsg = { message: string; position?: { file?: string; line?: number; column?: number } | null };
      const errors: BuildError[] = (err.errors as BunBuildMsg[]).map((e) => ({
        file: e.position?.file ?? "<unknown>",
        line: e.position?.line ?? 0,
        column: e.position?.column ?? 0,
        message: e.message,
      }));
      return { errors };
    }
    throw err;
  }
  const output = buildOutput.outputs[0];
  if (!output) {
    return {
      errors: [{ file: "<unknown>", line: 0, column: 0, message: "ui-leaf: Bun.build produced no output" }],
    };
  }
  return { js: await output.text() };
}

/** Assemble the final HTML page from compiled JS and options. */
function assembleHtml(opts: {
  js: string;
  title: string;
  csp: string | undefined;
  data: unknown;
  dataLoader: boolean;
}): string {
  const { js, title, csp, data, dataLoader } = opts;
  // Escape </script> sequences to prevent script-tag break-out.
  const safeJs = js.replace(/<\/script>/gi, "<\\/script>");

  const titleEscaped = title
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const cspMeta = csp
    ? `    <meta http-equiv="Content-Security-Policy" content="${csp.replace(/&/g, "&amp;").replace(/"/g, "&quot;")}" />\n`
    : "";

  // Double-stringify data: outer JSON.stringify produces a JSON string, then
  // escapeForScriptTag ensures </script> and U+2028/U+2029 can't break out.
  const dataInit = dataLoader
    ? "window.__UI_LEAF__ = {};"
    : `window.__UI_LEAF__ = { data: JSON.parse(${escapeForScriptTag(JSON.stringify(JSON.stringify(data ?? null)))}) };`;

  // Bootstrap: reads token from URL fragment, stashes it on __UI_LEAF__.token,
  // then immediately clears the fragment from the URL bar so the token is
  // never visible in history. On reload (fragment gone), sets sessionEnded so
  // the bundled module can render a friendly recovery message instead of
  // attempting unauthenticated fetches.
  // decodeURIComponent is wrapped in try/catch: a malformed %-sequence would
  // otherwise throw and kill the bootstrap silently; the catch falls through
  // to sessionEnded so the user gets the recovery screen instead of a blank page.
  const bootstrapScript = `${dataInit}
(function(){var m=/[#&]token=([^&#]*)/.exec(window.location.hash);if(m){try{window.__UI_LEAF__.token=decodeURIComponent(m[1]);history.replaceState(null,"",window.location.pathname+window.location.search);}catch(e){window.__UI_LEAF__.sessionEnded=true;}}else{window.__UI_LEAF__.sessionEnded=true;}})();`;

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${titleEscaped}</title>
${cspMeta}    <!-- ui-leaf bootstrap -->
    <script>${bootstrapScript}</script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module">${safeJs}</script>
  </body>
</html>`;
}

export async function compileView(opts: CompileOptions): Promise<CompileResult> {
  const {
    entry,
    viewsRoot,
    data,
    title = "ui-leaf",
    csp,
    // allowedHosts and token have no compile-time effect; accepted for API symmetry.
    allowedHosts: _allowedHosts,
    token: _token,
    dataLoader = false,
  } = opts;

  const viewsRootAbs = resolve(viewsRoot);
  const hasExt = /\.[a-z]+$/i.test(entry);
  const viewAbs = resolve(viewsRootAbs, hasExt ? entry : `${entry}.tsx`);
  if (!viewAbs.startsWith(viewsRootAbs + sep)) {
    return {
      html: "",
      errors: [
        {
          file: "<unknown>",
          line: 0,
          column: 0,
          message: `ui-leaf: view '${entry}' resolves outside viewsRoot`,
        },
      ],
    };
  }
  try {
    await stat(viewAbs);
  } catch {
    return {
      html: "",
      errors: [
        {
          file: viewAbs,
          line: 0,
          column: 0,
          message: `ui-leaf: view '${entry}' not found at ${viewAbs}`,
        },
      ],
    };
  }

  // Generate a temp entry that imports the resolved view, mounts React via
  // createRoot, and wires the mutation/heartbeat bridge.
  const tempDir = await mkdtemp(join(tmpdir(), "ui-leaf-compile-"));
  try {
    const entryPath = join(tempDir, "entry.tsx");

    const entryContent = dataLoader
      ? `import { createRoot } from "react-dom/client";
import View from ${JSON.stringify(viewAbs)};

const ctx = (globalThis as { __UI_LEAF__?: { token?: string; sessionEnded?: boolean } }).__UI_LEAF__ ?? {};
const token = ctx.token;

if (ctx.sessionEnded) {
  const root = document.getElementById("root");
  if (root) root.innerHTML = ${JSON.stringify(SESSION_ENDED_HTML)};
} else {
${SHARED_BRIDGE}

  async function bootstrap(): Promise<void> {
    const res = await fetch("/api/data", {
      headers: token ? { "X-UI-Leaf-Token": token } : {},
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error("ui-leaf: /api/data fetch failed (" + res.status + "): " + text);
    }
    let currentData: unknown = await res.json();
    const el = document.getElementById("root");
    if (!el) throw new Error("ui-leaf: #root element missing");
    const root = createRoot(el);
    root.render(<View data={currentData} mutate={mutate} />);
    subscribeEvents((ev) => {
      if (ev.type === "data-updated") {
        currentData = ev.data;
        root.render(<View data={currentData} mutate={mutate} />);
      } else if (ev.type === "view-swapped") {
        window.location.reload();
      } else if (ev.type === "closing") {
        el.innerHTML = ${JSON.stringify(CLOSED_OVERLAY_HTML)};
      }
    });
  }
  bootstrap();
}
`
      : `import { createRoot } from "react-dom/client";
import View from ${JSON.stringify(viewAbs)};

const ctx = (globalThis as { __UI_LEAF__?: { data?: unknown; token?: string; sessionEnded?: boolean } }).__UI_LEAF__ ?? {};
const token = ctx.token;

if (ctx.sessionEnded) {
  const root = document.getElementById("root");
  if (root) root.innerHTML = ${JSON.stringify(SESSION_ENDED_HTML)};
} else {
  let currentData: unknown = ctx.data;
${SHARED_BRIDGE}

  const el = document.getElementById("root");
  if (!el) throw new Error("ui-leaf: #root element missing");
  const root = createRoot(el);
  root.render(<View data={currentData} mutate={mutate} />);
  subscribeEvents((ev) => {
    if (ev.type === "data-updated") {
      currentData = ev.data;
      root.render(<View data={currentData} mutate={mutate} />);
    } else if (ev.type === "view-swapped") {
      window.location.reload();
    } else if (ev.type === "closing") {
      el.innerHTML = ${JSON.stringify(CLOSED_OVERLAY_HTML)};
    }
  });
}
`;

    await writeFile(entryPath, entryContent);

    const buildResult = await runBunBuild(entryPath);
    if ("errors" in buildResult) return { html: "", errors: buildResult.errors };

    return {
      html: assembleHtml({ js: buildResult.js, title, csp, data, dataLoader }),
      errors: [],
    };
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

/**
 * Compile an inline TSX source string into a full HTML page.
 *
 * The source is treated as a self-contained component; relative imports are
 * not supported (v1.0.0 constraint — the string has no filesystem context).
 * Bare-package imports (react, react-dom) work via the react-alias plugin.
 */
export async function compileSource(opts: CompileSourceOptions): Promise<CompileResult> {
  const { source, data, title = "ui-leaf", csp, token: _token } = opts;

  const tempDir = await mkdtemp(join(tmpdir(), "ui-leaf-src-"));
  try {
    // Write the caller's tsx as the view file, then write a thin entry wrapper.
    const viewPath = join(tempDir, "view.tsx");
    const entryPath = join(tempDir, "entry.tsx");

    await writeFile(viewPath, source);

    const entryContent = `import { createRoot } from "react-dom/client";
import View from ${JSON.stringify(viewPath)};

const ctx = (globalThis as { __UI_LEAF__?: { data?: unknown; token?: string; sessionEnded?: boolean } }).__UI_LEAF__ ?? {};
const token = ctx.token;

if (ctx.sessionEnded) {
  const root = document.getElementById("root");
  if (root) root.innerHTML = ${JSON.stringify(SESSION_ENDED_HTML)};
} else {
  let currentData: unknown = ctx.data;
${SHARED_BRIDGE}

  const el = document.getElementById("root");
  if (!el) throw new Error("ui-leaf: #root element missing");
  const root = createRoot(el);
  root.render(<View data={currentData} mutate={mutate} />);
  subscribeEvents((ev) => {
    if (ev.type === "data-updated") {
      currentData = ev.data;
      root.render(<View data={currentData} mutate={mutate} />);
    } else if (ev.type === "view-swapped") {
      window.location.reload();
    } else if (ev.type === "closing") {
      el.innerHTML = ${JSON.stringify(CLOSED_OVERLAY_HTML)};
    }
  });
}
`;

    await writeFile(entryPath, entryContent);

    const buildResult = await runBunBuild(entryPath);
    if ("errors" in buildResult) return { html: "", errors: buildResult.errors };

    return {
      html: assembleHtml({ js: buildResult.js, title, csp, data, dataLoader: false }),
      errors: [],
    };
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}
